### ISSUE TITLE
[suggestion] Consider using `Plugin#getDataFolder`

### ISSUE THREAD

**Issue by KingRainbow44** [Coooookies/Grasscutter-MeaMailPlus#1]
Instead of using `./plugins/(name)` plugins should consider switching to the `Plugin#getDataFolder` method introduced in `v1.0.3-dev`.

**Comment by KingRainbow44** [comment]
also just a maven suggestion, if you're depending on a file from the system use `${basedir}/` instead of using a direct path.
![image](https://user-images.githubusercontent.com/27646710/166389296-677f7daf-452a-4fd0-8c9f-32b02146e344.png)

**Comment by Coooookies** [comment]
> Instead of using `./plugins/(name)` plugins should consider switching to the `Plugin#getDataFolder` method introduced in `v1.0.3-dev`.

I will modify it later and use the plug-in path provided in config:
![image](https://user-images.githubusercontent.com/44562331/166421338-bf466f78-3bae-485e-933c-d434ac7cc380.png)

**Comment by Coooookies** [comment]
modified
