### ISSUE TITLE
非常感谢开发组人员，自昨天Grasscutter更新1.2.3后加载插件出错了

### ISSUE THREAD

**Issue by millet6** [Coooookies/Grasscutter-MeaMailPlus#12]
非常感谢开发组人员，这插件带给我很大的便利！但自昨天Grasscutter更新1.2.3后加载插件出错了，希望能早日修复，谢谢。
BUG日志如下：
![QQ截图20220723035241](https://user-images.githubusercontent.com/109255084/180517880-b029b66e-c784-46e4-b0b5-00d4aca334d8.png)

**Comment by Zhaokugua** [comment]
emm感觉你这个报错很奇怪，1.2.3也没删除getConfig方法怎么会报错没找到这个方法呢
要不你试试我昨天编译的版本，是基于1.2.3编译的
https://github.com/Zhaokugua/Grasscutter-MeaMailPlus

**Comment by millet6** [comment]
> emm感觉你这个报错很奇怪，1.2.3也没删除getConfig方法怎么会报错没找到这个方法呢 要不你试试我昨天编译的版本，是基于1.2.3编译的 [https://github.com/Zhaokugua/Grasscutter-MeaMailPlus ](https://github.com/Zhaokugua/Grasscutter-MeaMailPlus)

上面链接没有找到新的版本下载，我找到是旧的，项目怎么自己编译源码

**Comment by Zhaokugua** [comment]
> > emm感觉你这个报错很奇怪，1.2.3也没删除getConfig方法怎么会报错没找到这个方法呢 要不你试试我昨天编译的版本，是基于1.2.3编译的 [https://github.com/Zhaokugua/Grasscutter-MeaMailPlus ](https://github.com/Zhaokugua/Grasscutter-MeaMailPlus)
> 
> 上面链接没有找到新的版本下载，我找到是旧的，项目怎么自己编译源码

我发我release里了（

**Comment by millet6** [comment]
> > > emm感觉你这个报错很奇怪，1.2.3也没删除getConfig方法怎么会报错没找到这个方法呢 要不你试试我昨天编译的版本，是基于1.2.3编译的  [https://github.com/Zhaokugua/Grasscutter-MeaMailPlus  ](https://github.com/Zhaokugua/Grasscutter-MeaMailPlus)
> > 
> > 
> > 上面链接没有找到新的版本下载，我找到是旧的，项目怎么自己编译源码
> 
> 我发我release里了（

[MeaMailPlus-1.0-SNAPSHOT.jar](https://github.com/Zhaokugua/Grasscutter-MeaMailPlus/releases/download/v1.0.3-fix2/MeaMailPlus-1.0-SNAPSHOT.jar)  MeaMailPlus-1.0-SNAPSHOT.jar这个吗？

**Comment by millet6** [comment]
很可惜 从新下的插件报错 我用的 grasscutter-1.2.3-dev.jar 这里能下载 https://ci.grasscutter.ga/job/Grasscutter-Dev/

**Comment by Zhaokugua** [comment]
> 很可惜 从新下的插件报错 我用的 grasscutter-1.2.3-dev.jar 这里能下载 https://ci.grasscutter.ga/job/Grasscutter-Dev/

如果还是和之前一样的报错的话那真的很奇怪
我两小时前刚从dev分支clone了最新的代码编译都没有问题
或许你应该考虑换一个jar包

**Comment by millet6** [comment]
我怎么自己编译你的代码

**Comment by Zhaokugua** [comment]
> 我怎么自己编译你的代码

如果你说的是meamail这个插件的话，编译好的版本已经放在我的release里面了，不需要你自己编译
如果你确实需要自己编译，只需要下载源代码然后使用marven就可以自动构建好这个插件的jar包

如果你说的是Grasscutter的话，按照官方readme的方法，从官服仓库下载好源代码之后使用gradlew直接编译即可，当然他的actions里面也有自动构建的版本可以直接下载

**Comment by millet6** [comment]
> 

我说的是meamail这个插件，请问可以利用 github上的actios 来编译吗？

**Comment by Zhaokugua** [comment]
> > 
> 
> 我说的是meamail这个插件，请问可以利用 github上的actios 来编译吗？

应该是可以的，不过需要自己配置一下，因为这个更新并不频繁感觉也不需要配置（
