### ISSUE TITLE
Config file restoring to default

### ISSUE THREAD

**Issue by Nekoniria** [Coooookies/Grasscutter-MeaMailPlus#4]
This has gotten rather annoying as I have no idea whats causing it.
I set the config, open the server, everything works fine, then I close the server to make edits somewhere else, open the server and the config file restored to default. 
No errors or warnings...

**Comment by Coooookies** [comment]
can u send a screenshot of config?

**Comment by Coooookies** [comment]
> This has gotten rather annoying as I have no idea whats causing it. I set the config, open the server, everything works fine, then I close the server to make edits somewhere else, open the server and the config file restored to default. No errors or warnings...
can u send a screenshot of config?

**Comment by Coooookies** [comment]
> This has gotten rather annoying as I have no idea whats causing it. I set the config, open the server, everything works fine, then I close the server to make edits somewhere else, open the server and the config file restored to default. No errors or warnings...

can u send a screenshot of config?

**Comment by Coooookies** [comment]
![image](https://user-images.githubusercontent.com/44562331/169055669-25967696-6366-4bf0-b0f0-d722eb7d9f76.png)
it looks like a mistake name.
did u modify the configuration class of plugin yourself ?

**Comment by Coooookies** [comment]
> @Coooookies Oh, can I not add/edit the name of the templates?

u can name ur template file like this:
![image](https://user-images.githubusercontent.com/44562331/169065871-67c498a9-123e-464b-ae0d-6ead61fb6cde.png)

templateid is the unique identifier of the template:
![image](https://user-images.githubusercontent.com/44562331/169066559-ced1b53e-e814-4e55-9236-e1f58533b5ba.png)
