### ISSUE TITLE
求助，不太会用

### ISSUE THREAD

**Issue by vomirio** [Coooookies/Grasscutter-MeaMailPlus#6]
我每次重新启动服务器config.json里面的内容就还原了···     配置完后，在Console中输入/meamail reload即可重载配置文件。  这一步不太明白 Console这个是个啥控制台？  感谢大佬···救救孩子

**Comment by Coooookies** [comment]
> 我每次重新启动服务器config.json里面的内容就还原了··· 配置完后，在Console中输入/meamail reload即可重载配置文件。 这一步不太明白 Console这个是个啥控制台？ 感谢大佬···救救孩子

console就是服务器控制台哦，具体的可以看中文文档
